### ISSUE TITLE
Backtest new strategy in cryptowat.ch

### ISSUE THREAD

**Issue by rootkc** [rootkc/rxjs-trading-bot#12]
## Issue Description
Backtest the following strategy in cryptowat.ch http://www.daytradingsite.com/day-trading-system-scalping-1-minute-charts/

## Possible Solution
Validate if it makes sense to implement it

## Acceptance Criteria
Strategy makes profit

## Related Story / issue

**Comment by Kisgus** [comment]
Done, we have made custom UI for this now
