### ISSUE TITLE
Pass unit testing

### ISSUE THREAD

**Issue by Kisgus** [rootkc/rxjs-trading-bot#5]
## Issue Description

The bot needs to be able to pass unit-testing in order to prove-ably be able to work as intended

## Possible Solution

Conduct unit testing to be able to satisfy our acceptance criteria for moving to platform integration 

## Acceptance Criteria

Based on paper-testing data the bot needs to be to:

- [x] Execute on buy signals as intended

- [x] Execute on sell signals on intended

- [x] Execute stop/loss when our risk ratio is reached as expected

- [x] Do not execute without appropriate signals

## Related Story / issue

**Comment by Kisgus** [comment]
1st data-testing-draft:

![screen shot 2018-06-11 at 7 52 46 pm](https://user-images.githubusercontent.com/18598519/41283665-78fb3684-6e37-11e8-82f4-1eba6907226c.png)

**Comment by rootkc** [comment]
Investigate how to either download or input data into tradeview
